# docker-compose -f src/Together.Docker/docker-compose.env.yml -p env-v3-together up -d
version: "3.8"

volumes:
  env-v3-together-postgres-data: {}
  env-v3-together-redis-data: {}

services:
  env-v3-together-postgres:
    container_name: env-v3-together-postgres
    image: postgres
    environment:
      - POSTGRES_DB=Together.NET.v3
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - env-v3-together-postgres-data:/var/lib/postgresql/data/

  env-v3-together-redis:
    container_name: env-v3-together-redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - env-v3-together-redis-data:/data
  
  env-v3-together-rabbitmq:
    container_name: env-v3-together-rabbitmq
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"     # AMQP protocol
      - "15672:15672"   # UI management